version: '3.4'

services:
  webapp:
    build: .
    ports:
      - 5100:80
      - 5101:443
      
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
      - '5672:5672'
        # HTTP management UI
      - '15672:15672'